### PR TITLE
Temperature Conversion Functions

### PR DESCRIPTION
**Pull request by stimpsonsg**
Adds temperature conversion functions and unit testing.

### CODE REVIEW

**Comment by HendersonSC** [comment]
I agree with @aarograh I think it is perfectly reasonable to expect the client to only use physically meaningful temperatures.

**Comment by stimpsonsg** [comment]
Alright, I agree that the DBC check is of minimal benefit.  Upgraded all routines to elemental.

**Comment by stimpsonsg** [comment]
when the heck is this CI ever going to fire off?

**Comment by aarograh** [comment]
The build has passed: https://travis-ci.org/github/CASL/Futility

Something's up with the Travis to Github status update, but the code itself is fine.  Merging this in

**Pull request merged**
