### PR TITLE
Added the "Merge Request Review Checklist" document to the doc directory

### PR DESCRIPTION
**Pull request by thfolk**
Ticket #6138 "Add a Merge Request Checklist to Futility Repo"

### CODE REVIEW

**Comment by bkochuna** [comment]
@aarograh or @stimpsonsg This is what I sent over email. Do either of you want to review and approve here?

This PR just adds a PDF to the repo.

**Comment by bkochuna** [comment]
@aarograh and @stimpsonsg 

I plan to merge this tomorrow (after the stand-up), if you would like to approve (again) here, can you do so by then? If not, I'll just go ahead merge around lunch time.

**Comment by aarograh** [comment]
Sorry, was out on travel last week and had visitors here at ORNL the last few days so I forgot about this.  The checklist looks good to me.  This should be helpful in standardizing our merge/review process.

**Comment by bkochuna** [comment]
Thanks @aarograh!

**Pull request merged**
