### PR TITLE
Redirect .APPROXEQ. operator to .APPROXEQA.

### PR DESCRIPTION
**Pull request by aarograh**
The string comparisons done by .APPROXEQ. have been no end of
trouble, whether from major performance degredation or causing
confusion and time-wasting for new developers.  The APPROXEQA,
APPROXEQF, APPROXEQR operators and SOFTEQ function suffice for
all comparisons that have been needed so far.  This commit points
.APPROXEQ. to the same procedures as .APPROXEQA. to prevent
breaking any packages that have used .APPROXEQ.

### CODE REVIEW

**Comment by aarograh** [comment]
Well, bad news... MPACT is not going to take this as nicely as I expected:

`         63 - MPACT_libsThermalExpandXML_testTEXML_ExpandAxial (Failed)
         67 - MPACT_libsReactor_testMaterialTypes (Failed)
         75 - MPACT_libsReactor_testPins (Failed)
        105 - MPACT_libsCoreSolvers_testMultiStateSolver (Failed)
        134 - MPACT_libsMOC_testMOCSweeper_2D1D_P0_MOM (Failed)
        135 - MPACT_libsMOC_testMOCSweeper_2D1D_P0MG_MOM (Failed)
        144 - MPACT_libsNodal_testNodalKernel (Failed)
        154 - MPACT_libsCMFD_testMultigridCMFD (Failed)
        169 - MPACT_libsXS_testXSLibsORNLv4 (Failed)
        178 - MPACT_libsEditsVariables_testEditsVar_FluxExtensions (Failed)
        189 - MPACT_libsFeedback_testFuelTempTable (Failed)
        205 - MPACT_libsTransient_testTransientFSS (Failed)
        209 - MPACT_libsTransient_testPointKinetics (Failed)
        215 - MPACT_libsPostOps_testPostOp_ShiftCoupling (Failed)
`

**Comment by stimpsonsg** [comment]
Yum

**Comment by aarograh** [comment]
MPACT merge request is in that updates unit tests in a way that will allow this merge to go through without breaking anything.

**Comment by aarograh** [comment]
Also need to tweak a mongoose test to use the APPROXEQA/SOFTEQ operators too before this goes in.

**Pull request merged**
