### PR TITLE
Strings cleanup

### LINKED ISSUE #217: Remove strrep and other defunct string subroutines (Follow-up work to #216)
Updated methods were added to the StringType class in #216 .  These methods deprecate old subroutines that are currently used in downstream codes.  Once the deprecated calls are removed from those codes, the subroutines should be deleted from Strings.

### PR DESCRIPTION
**Pull request by HendersonSC**
Clean up formatting, Remove defunct routines. This commit resolves #217

### CODE REVIEW

**Comment by stimpsonsg** [comment]
have you verified that this passes on MPACT/CTF/MAMBA?

**Comment by HendersonSC** [comment]
Built MPACT with CTF and MAMBA and all of the tests passed. I still need to double check a standalone CTF build.

**Comment by HendersonSC** [comment]
All the standalone CTF test passed as well

**Comment by stimpsonsg** [comment]
great!  I'm going to hold this till tomorrow

**Pull request merged**
