### PR TITLE
Add replace_entry interface to ArrayUtils

### PR DESCRIPTION
**Pull request by aarograh**
This allows a single entry of an array to be replaced by an array.  It's basically a convenience function to handle certain types of array resize operations.

### CODE REVIEW

**Review by HendersonSC — APPROVED** [review]
Looks to be in good shape.

**Comment by djabaay** [comment]
Just curious @aarograh, where did you find yourself seeing this operation used a bunch?

**Comment by aarograh** [comment]
@HendersonSC I'm going to push up a unit test in a bit before we merge this

@djabaay I reworked editsFactory in MPACT and there are several spots I use this there to expand the user-defined edits groups

**Comment by HendersonSC** [comment]
Yeah good point, this is why I shouldn't review thing later in the night.

**Comment by HendersonSC** [comment]
Unit test is definitely a good add. I am good with this as is.

**Pull request merged**
