### PR TITLE
Changing .travis.yml to use && instead of ;

### PR DESCRIPTION
**Pull request by bkochuna**
Description:
In bash when chaining commands, the && will only execute the next
command if the previous command had a return value of 0. When using
; it will execute the next command regardless of the return code.

Not sure how TravisCI treats the error code in reporting errors,
so I'm hoping this reveals the issue.

Github Issue - #132

### CODE REVIEW

**Comment by bkochuna** [comment]
Followed this build on travis-ci and it definitely returns a failed status after replacing `;` with `&&`.
See here: https://travis-ci.org/CASL/Futility/jobs/603104260

**Comment by bkochuna** [comment]
Don't know why this page didn't update. But. The build passed on travis-ci here:
https://travis-ci.org/CASL/Futility/builds/603108633

**Comment by bkochuna** [comment]
@stimpsonsg will you have time to review?

**Comment by stimpsonsg** [comment]
yeah, I'll get to it today

**Pull request merged**
