### PR TITLE
Assign reals

### PR DESCRIPTION
**Pull request by djabaay**

### CODE REVIEW

**Comment by bkochuna** [comment]
So does this fix Scott’s issue with null characters?

**Comment by djabaay** [comment]
@bkochuna It does not.  This is functionality I wanted for making the error message in setVars in the state object simpler.  I want to print the min and max valid values for a given state variable, and I'd rather not write reals to characters to strings while just writing integers to strings.

**Comment by djabaay** [comment]
@bkochuna If you have some time to kill, feel free.

**Comment by djabaay** [comment]
@bscollin I know, I was thinking the same thing previously.  The issue at hand is that we are overloading the assignment operator, so there is no place for the optional format argument of which I was thinking.  If you're worried about discrepancies between systems and builds producing a different 15th digit, we can change the default to something less than 15.  What do you think would be an acceptable accuracy that is build and system consistent?

**Comment by djabaay** [comment]
@zdodson94 Nice test Zack, glad it works for that case too!  It could be worth it for the TINY operation, just to cover all the bases.

**Comment by bkochuna** [comment]
I also want stress, that this is relatively low priority for compared to other problems.

**Comment by bscollin** [comment]
@djabaay, I think you're right to do full digits by default.  I was thinking about maybe having a editor object which stores the number of digits for outputs but that's way outside of the scope of this ticket.

**Comment by bscollin** [comment]
Whats the hold up on merging this?

**Comment by bscollin** [comment]
@djabaay @bkochuna can we merge this?

**Comment by djabaay** [comment]
I am ok merging it.

**Comment by bscollin** [comment]
done.  it was sitting there

**Pull request merged**
