### PR TITLE
Refactor MPACT Debug Build Flags

### PR DESCRIPTION
**Pull request by jpjones6**
Change set of gcc flags for debug build to warn for more problems and to increase performance using -Og (gcc's debug specific optimization level). Speeds up debug build by a factor of ~2 while not increasing compile time. This work is part of #6196.

### CODE REVIEW

**Comment by stimpsonsg** [comment]
To verify...you've run what level of regression tests?

**Comment by jpjones6** [comment]
Basic

**Comment by stimpsonsg** [comment]
Okay...since it's debug, let's at least verify it with CONTINUOUS, but should be good.

**Comment by jpjones6** [comment]
All CONTINUOUS tests passed.

**Comment by stimpsonsg** [comment]
alright, let's see what's up

**Pull request merged**
